server:
  port: 8080

logging:
  level:
    root: INFO

---
spring:
  profiles: embedded
  h2:
    #To access h2sql console http://localhost:8080/console and copy/paste the datasource.url
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:gfit;Mode=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: create-drop
    #activate this option if we want to inject our schema
    #hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.format_sql: true
  activate:
    session: true

